route:
    receiver: 'email'

receivers:
    - name: 'email'
      email_configs:
          - to: 'williamtfligor@gmail.com'
            from: 'williamtfligor@gmail.com'
            smarthost: 'smtp.google.com'
