global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        monitor: my-project
rule_files:
    - alert.rules

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - 'alertmanager:9093'
scrape_configs:
    - job_name: prometheus
      scrape_interval: 5s
      static_configs:
        - targets:
            - 'localhost:9090'
    - job_name: cadvisor
      scrape_interval: 5s
      dns_sd_configs:
        - names:
            - tasks.cadvisor
          type: A
          port: 8080
      static_configs:
        - targets:
            - 'cadvisor:8080'
    - job_name: gitlab
      scrape_interval: 5s
      dns_sd_configs:
        - names:
            - tasks.gitlab
          type: A
          port: 9999
      static_configs:
        - targets:
            - 'gitlab:80'
