global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        monitor: monitor
rule_files:
    - alert_rules.yml

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - 'alertmanager:9093'
scrape_configs:
    - job_name: prometheus
      scrape_interval: 5s
      static_configs:
        - targets:
            - 'localhost:9090'
    - job_name: cadvisor
      scrape_interval: 5s
      static_configs:
        - targets:
            - 'cadvisor:8080'
    - job_name: node-exporter
      scrape_interval: 5s
      static_configs:
        - targets:
            - 'node-exporter:9100'
    - job_name: gitlab
      scrape_interval: 10s
      static_configs:
        - targets:
            - 'gitlab:9118'
