{
 "title": "Gitlab",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failing Masters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_status{ref=\"master\",status=\"master\"}==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Failing Develops",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_status{ref=\"develop\",status=\"failed\"}==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Main Branch Status",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "expr": "gitlab_ci_pipeline_status==1" }
   ]
  }
 ]
}