{
 "title": "Server Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   }
  ]
 },
 "panels": [
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ALERTS) or vector(0)" }
   ]
  },
  {
   "title": "Gitlab Runner Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    { "expr": "gitlab_runner_status" }
   ]
  },
  { "title": "Host - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "host" },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$host\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Average CPU Load (5m)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$host\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$host\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$host\",mountpoint=\"/\",fstype=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$host\",mountpoint=\"/\",fstype=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$host\"}[3m])) / 1e6"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$host\"}[3m])) / 1e6"
    }
   ]
  },
  { "title": "Host - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$host\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Average CPU Load (5m)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$host\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$host\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$host\",mountpoint=\"/\",fstype=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$host\",mountpoint=\"/\",fstype=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$host\"}[3m])) / 1e6"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$host\"}[3m])) / 1e6"
    }
   ]
  }
 ]
}